---
name: Tado Optimiser
version: 2024.12.11.15
slug: tado_optimiser
description: Tado Optimiser
url: https://github.com/charlie-chester/tado_optimiser
codenotary: m.chester@me.com
ingress: True
ingress_port: 5052
ingress_root: "/"
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
hassio_api: true
hassio_role: admin
auth_api: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  log_level:
  latitude:
  longitude:
  open_weather_api:
  octopus_api:
  octopus_account:
schema:
  log_level: list(debug|info|notice|warning|error)?
  latitude: str
  longitude: str
  open_weather_api: str
  octopus_api: str
  octopus_account: str