# If you want to control Tado then change to true and set the room names as per your Tado setup
# You will need to restart the addon after making changes

control_tado: True
outside_temp: 12
sun_correction_temp: 10
rooms:
  conservatory:
    day: 18
    evening: 18
    night: 17
    sun_correction: 2
  dining_room:
    day: 18
    evening: 20
    night: 17
    sun_correction: 0
  lounge:
    day: 18
    evening: 20
    night: 17
    sun_correction: 0
  office:
    day: 17
    evening: 17
    night: 17
    sun_correction: 0
  bedroom:
    day: 17
    evening: 17
    night: 17
    sun_correction: 0
  pink_room:
    day: 17
    evening: 17
    night: 17
    sun_correction: 0
