rooms:
  conservatory:
    day: 18
    evening: 18
    night: 17
    sun_correction: 2
  dining_room:
    day: 18
    evening: 18
    night: 17
    sun_correction: 0
  lounge:
    day: 18
    evening: 20
    night: 17
    sun_correction: 0
  office:
    day: 17
    evening: 17
    night: 17
    sun_correction: 0
  bedroom:
    day: 17
    evening: 17
    night: 17
    sun_correction: 0
  pink_room:
    day: 17
    evening: 17
    night: 17
    sun_correction: 0